name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the app
        run: xcodebuild -scheme YourSchemeName -sdk macosx -configuration Debug build

      - name: Run tests
        run: xcodebuild test -scheme YourSchemeName -sdk macosx -configuration Debug -destination 'platform=macOS'
